repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        args: [--fix, --line-length=110]
      - id: ruff-format
        args: [--line-length=110]

  - repo: local
    hooks:
      - id: no-push-to-main
        name: Prevent direct push to main
        entry: bash -c 'if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then echo "STOP! Do not push directly on main branch. Checkout development branch."; exit 1; fi'
        language: system
        stages: [pre-push]