"""initial migration

Revision ID: a3824df86db8
Revises:
Create Date: 2026-04-10 18:10:46.983627

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3824df86db8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_example_table")),
    )
    op.create_index(op.f("ix_example_table_id"), "example_table", ["id"], unique=False)
    op.create_index(op.f("ix_example_table_name"), "example_table", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_example_table_name"), table_name="example_table")
    op.drop_index(op.f("ix_example_table_id"), table_name="example_table")
    op.drop_table("example_table")
    # ### end Alembic commands ###
